import type { Metadata } from 'next';
import { Geist, Geist_Mono, Russo_One } from 'next/font/google';
import './globals.css';

const russo_one = Russo_One({
    subsets: ['latin'],
    variable: '--font-russo-one',
    weight: '400',
    display: 'swap',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body
                className={`${geistSans.variable} ${geistMono.variable} ${russo_one.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
